# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos-6.5"
  config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.1/centos65-x86_64-20131205.box"

  config.vm.synced_folder "./vshell_v1", "/home/vagrant/vshell_v1", create: true

  config.vm.network :forwarded_port, guest: 80, host: 8810
  config.vm.network :public_network, :bridge => 'en1: Wi-Fi (AirPort)'

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end

  config.vm.provision :shell, :path => "bootstrap.sh"

end
